# Generated by Django 3.1.6 on 2021-02-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_auto_20210212_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='hidden',
        ),
    ]
