# Generated by Django 3.1.6 on 2021-02-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_remove_notice_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='exp_date',
            field=models.DateField(verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
