# Generated by Django 3.1.6 on 2021-02-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_auto_20210217_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='exp_date',
            field=models.DateTimeField(verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
